Mercury = planet("Mercury", 40, "Grey")
Venus = planet("Venus", 80, "Yellow")
Earth = planet("Earth", 100, "Blue")
Mars = planet("Mars", 150, "Red")
Jupiter = planet("jupter", 180, "Brown")
Saturn = planet("Saturn", 230, "pink")
Uranus = planet("Uranus", 250, "light blue")
Neptune = planet("Neptune", 250, "Black")